### PR TITLE
Allow global options to be applied to each request

### PR DESCRIPTION
**Pull request by bigbam505**
Would allow options like ignore ssl cert to be passed in globally.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Seems reasonable to me. Actually had the same request with `client-oauth2` in the past, would you mind following a similar approach here? See https://github.com/mulesoft/js-client-oauth2#usage for more information. Seems reasonable to only support `options` here though, I just don't want to pollute all options with Popsicle options.

**Comment by bigbam505** [comment]
So I am trying to see what you mean by that exactly and I am not sure I 100% follow.  I don't see where you can actually set a global flag in the js-client-oauth2 nor the similarity in the libraries so if you could help clarify I can make a change to accommodate.

**Comment by blakeembrey** [comment]
Mostly it comes down to them both making HTTP requests and both needing the same feature (set `options` in Popsicle to disable strict SSL). Instead of merging all the options with request options, which will merge lots of potentially breaking things one day, just set `reqOpts.options = options.options`. This will let you override it the same as usual, but we don't have to think about any future fields causing trouble.

If you make this change, just ping me again. You'll need to sign the MuleSoft CLA before merging though: https://api-notebook.anypoint.mulesoft.com/notebooks#bc1cf75a0284268407e4

**Comment by bigbam505** [comment]
Took me a second to figure out your point but I see now that popsicle has an options section that you are passing in.  Way to many `options.options.options` nesting.  I made some changes as well to follow the pattern of the other library  you referenced because it seems like a cleaner pattern to follow.

**Comment by blakeembrey** [comment]
Awesome, cheers!

**Pull request merged**
